# Generated by Django 3.1.12 on 2025-04-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='static/images')),
                ('date_posted', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='static/images')),
                ('date_posted', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Concert News', max_length=100)),
                ('image', models.FileField(upload_to='static/images')),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='static/images')),
                ('date_posted', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concert.album')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='concert.cart')),
                ('merchandise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concert.merchandise')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concert.tickets')),
            ],
        ),
    ]
